# ============================================================
# 同花顺 iFinD HTTP API 配置
# ============================================================

# ----- 认证信息 -----
# refresh_token 需要从 Windows 版超级命令工具获取（只需获取一次）
# 获取方法见 README.md
IFIND_REFRESH_TOKEN = "eyJzaWduX3RpbWUiOiIyMDI2LTAyLTAyIDE0OjIzOjQ5In0=.eyJ1aWQiOiI2ODY0MjMzODciLCJ1c2VyIjp7ImFjY2Vzc1Rva2VuIjoiYjZmYTZiMWU0OTQ1Njc5YzgyYmI0MWRhOWNhNDNhNmU0MjBlODU5ZC5zaWduc19OamcyTkRJek16ZzMiLCJhY2Nlc3NUb2tlbkV4cGlyZWRUaW1lIjoiMjAyNi0wMi0wMiAxNDoyMzo0OSIsImFjY291bnQiOiJ4bXh5Mzk5IiwiYXV0aFVzZXJJbmZvIjp7IkVleGNlbFBheWVycyI6IjE3NzQ5MjAzMDEwMDAifSwiY29kZUNTSSI6W10sImNvZGVaekF1dGgiOltdLCJoYXNBSVByZWRpY3QiOmZhbHNlLCJoYXNBSVRhbGsiOmZhbHNlLCJoYXNDSUNDIjpmYWxzZSwiaGFzQ1NJIjpmYWxzZSwiaGFzRXZlbnREcml2ZSI6ZmFsc2UsImhhc0ZUU0UiOmZhbHNlLCJoYXNGYXN0IjpmYWxzZSwiaGFzRnVuZFZhbHVhdGlvbiI6ZmFsc2UsImhhc0hLIjp0cnVlLCJoYXNMTUUiOmZhbHNlLCJoYXNMZXZlbDIiOmZhbHNlLCJoYXNSZWFsQ01FIjpmYWxzZSwiaGFzVHJhbnNmZXIiOmZhbHNlLCJoYXNVUyI6ZmFsc2UsImhhc1VTQUluZGV4IjpmYWxzZSwiaGFzVVNERUJUIjpmYWxzZSwibWFya2V0QXV0aCI6eyJEQ0UiOmZhbHNlfSwibWF4T25MaW5lIjoxLCJub0Rpc2siOmZhbHNlLCJwcm9kdWN0VHlwZSI6IlNVUEVSQ09NTUFORFBST0RVQ1QiLCJyZWZyZXNoVG9rZW5FeHBpcmVkVGltZSI6IjIwMjYtMDMtMzEgMDk6MjU6MDEiLCJzZXNzc2lvbiI6ImRkNmJhNWIyZjgxODViMDdmNTgyNThlOWQ1ZTU2NjhhIiwic2lkSW5mbyI6ezY0OiIxMTExMTExMTExMTExMTExMTExMTExMTEiLDE6IjEwMSIsMjoiMSIsNjc6IjEwMTExMTExMTExMTExMTExMTExMTExMSIsMzoiMSIsNjk6IjExMTExMTExMTExMTExMTExMTExMTExMTEiLDU6IjEiLDY6IjEiLDcxOiIxMTExMTExMTExMTExMTExMTExMTExMDAiLDc6IjExMTExMTExMTExIiw4OiIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMSIsMTM4OiIxMTExMTExMTExMTExMTExMTExMTExMTExIiwxMzk6IjExMTExMTExMTExMTExMTExMTExMTExMTEiLDE0MDoiMTExMTExMTExMTExMTExMTExMTExMTExMSIsMTQxOiIxMTExMTExMTExMTExMTExMTExMTExMTExIiwxNDI6IjExMTExMTExMTExMTExMTExMTExMTExMTEiLDE0MzoiMTEiLDgwOiIxMTExMTExMTExMTExMTExMTExMTExMTEiLDgxOiIxMTExMTExMTExMTExMTExMTExMTExMTEiLDgyOiIxMTExMTExMTExMTExMTExMTExMTAxMTAiLDgzOiIxMTExMTExMTExMTExMTExMTEwMDAwMDAiLDg1OiIwMTExMTExMTExMTExMTExMTExMTExMTEiLDg3OiIxMTExMTExMTAwMTExMTEwMTExMTExMTEiLDg5OiIxMTExMTExMTAxMTAxMDAwMDAwMDExMTEiLDkwOiIxMTExMTAxMTExMTExMTExMTAwMDExMTExMCIsOTM6IjExMTExMTExMTExMTExMTExMDAwMDExMTEiLDk0OiIxMTExMTExMTExMTExMTExMTExMTExMTExIiw5NjoiMTExMTExMTExMTExMTExMTExMTExMTExMSIsOTk6IjEwMCIsMTAwOiIxMTExMDExMTExMTExMTExMTEwIiwxMDI6IjEiLDQ0OiIxMSIsMTA5OiIxIiw1MzoiMTExMTExMTExMTExMTExMTExMTExMTExIiw1NDoiMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLDU3OiIwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMCIsNjI6IjExMTExMTExMTExMTExMTExMTExMTExMSIsNjM6IjExMTExMTExMTExMTExMTExMTExMTExMSJ9LCJ0aW1lc3RhbXAiOiIxNzcwMDEzNDI5Mjg0IiwidHJhbnNBdXRoIjpmYWxzZSwidHRsVmFsdWUiOjAsInVpZCI6IjY4NjQyMzM4NyIsInVzZXJUeXBlIjoiRlJFRUlBTCIsIndpZmluZExpbWl0TWFwIjp7fX19.F4B6C3F7E0405F6FEE68F1147A99A5956597573664A550464FACFFE7DA74E52D"

# API 基础地址（不要修改）
IFIND_BASE_URL = "https://quantapi.51ifind.com/api/v1"

# ----- 期货合约代码 -----
# 沪镍主力合约
NICKEL_MAIN = "niZL.SHF"
# 不锈钢主力合约
SS_MAIN = "ssZL.SHF"
# 所有要监控的合约
WATCH_LIST = [NICKEL_MAIN, SS_MAIN]

# ----- 数据存储路径 -----
import os
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(PROJECT_ROOT, "data")
RAW_DIR = os.path.join(DATA_DIR, "raw")
PROCESSED_DIR = os.path.join(DATA_DIR, "processed")
MANUAL_DIR = os.path.join(DATA_DIR, "manual")
LOG_DIR = os.path.join(PROJECT_ROOT, "logs")

# ----- 价格监控阈值 -----
# 日涨跌幅超过此值触发提醒（百分比）
PRICE_ALERT_THRESHOLD = 2.0
# 持仓量变化超过此值触发提醒（百分比）
OI_ALERT_THRESHOLD = 5.0

# ----- 微信推送（企业微信机器人）-----
# 后续配置，先留空
WECHAT_WEBHOOK_URL = ""
